sudoku_site/sudoku_app/urls.py
from django.urls import path, include

from . import views

app_name = 'sudoku_app'

urlpatterns = [
    path('home/', views.home,name="home"),
    path('', views.home, name='home'),
    path('play/', views.play, name='play'),
    path('new_puzzle_from_diff_level_change', views.new_puzzle_from_diff_level_change, name='new_puzzle_from_diff_level_change'),
    path('new_puzzle', views.new_puzzle, name='new_puzzle'),
    path('play/<int:puzzle_id>', views.new_specific_puzzle, name='new_specific_puzzle'),
    path('sign_up/', views.sign_up,name='sign_up'),
    path('user/<int:user_id>/', views.user_page, name="user_page"),
    path('record_successful_puzzle/', views.record_successful_puzzle, name="record_successful_puzzle"),
]

sudoku_site/sudoku_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('sudoku_app.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls"))
]

sudoku_site/sudoku_app/models.py
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User
from django.db import models

class Game(models.Model):
    EASY = 'Easy'
    MEDIUM = 'Medium'
    HARD = 'Hard'
    EXPERT = 'Expert'
    
    DIFFICULTY_LEVELS = [
        (EASY, 'Easy'),
        (MEDIUM, 'Medium'),
        (HARD, 'Hard'),
        (EXPERT, 'Expert'),
    ]

    hints_board = ArrayField( ArrayField(models.IntegerField(), size=9), size=9)
    solved_board = ArrayField( ArrayField(models.IntegerField(), size=9), size=9)
    difficulty = models.CharField(max_length = 50, choices = DIFFICULTY_LEVELS, default=EASY)
    

class SolvedGame(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE) #The game being solved
    user = models.ForeignKey(User, on_delete=models.CASCADE) #the user who solved it
    time_started = models.DateTimeField() #Time when the solution started
    time_solved = models.DateTimeField() #Time when correct solution was submitted

sudoku_site/sudoku_app/forms.py
from enum import unique
from django import forms
from .models import Game
from django.forms import ValidationError
from django.contrib.auth.forms import UserCreationForm,PasswordResetForm
from django.contrib.auth.models import User
from django_recaptcha.fields import ReCaptchaField

class GameSettingsForm(forms.Form):
    LEISURE = 'Leisure'
    TIMED = 'Timed' #NOTE This is picked up by JS. If changed, JS need toc hange as well
    GAME_TYPES = [
        (LEISURE, 'Leisure'),
        (TIMED, 'Timed'),
    ]
    ID_OF_GAME_TYPE_ELEMENT = 'id_game_type' #NOTE this is picked up by JS. If you cahnge this, change JS as well.

    difficulty_level = forms.ChoiceField(choices=Game.DIFFICULTY_LEVELS, label='Difficulty',\
                                     widget=forms.Select(attrs={'onchange': 'submit();'}))
    
    game_type = forms.ChoiceField(choices=GAME_TYPES, label='Type',\
                                     widget=forms.Select(attrs={'onchange': 'submit();', 'id': ID_OF_GAME_TYPE_ELEMENT}))


class SignUpForm(UserCreationForm):

    email = forms.EmailField(required=True, help_text="Required. Enter a valid email address")
    captcha = ReCaptchaField()

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    
    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("A user with the same email already exists")
        return self.cleaned_data

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

sudoku_site/sudoku_app/views.py
import re
import datetime
import json
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from django.urls import reverse
from django.template import loader
from .models import Game,SolvedGame
from .db_generation import GenerateDatabase
from .game_logic import GetOneAlreadySolvedPuzzle,GetOnePuzzliWithOneEmptyColumn
import random

from sudoku_app.forms import GameSettingsForm,SignUpForm

def home(request):
    template = loader.get_template('sudoku_app/home.html')
    user_id=-1
    
    if request.user.is_authenticated:
        user_id = request.user.id
    context = {
        'user_id' : user_id
    }
    return HttpResponse(template.render(context, request))  

def play(request):
    
    if (Game.objects.all().count()==0):
        GenerateDatabase(1,1,0,0,11814);#If db is empty, generate one easy and one medium
    
    #for testing only
    #solved_puzzle = GetOnePuzzliWithOneEmptyColumn()
    #hint_board = solved_puzzle["board_with_hints"]
    #sol_board = solved_puzzle["solved_board"]
    #alreday_solved_game = Game.objects.create(hints_board = hint_board, solved_board = sol_board, difficulty=Game.EXPERT)
    #print(alreday_solved_game.id)

    game_objects = Game.objects.filter(difficulty = Game.EASY)
    sel_idx = random.randint(0,game_objects.count()-1)
    sel_id = game_objects[sel_idx].id
    request.session['game_type'] = GameSettingsForm.LEISURE #If user lands without any puzzle, start in leisure mode
    return HttpResponseRedirect(reverse('sudoku_app:new_specific_puzzle',  kwargs={'puzzle_id': sel_id}));

def sign_up(request):
    if request.method == 'POST':
        sign_up_form = SignUpForm(request.POST)
        if sign_up_form.is_valid():
            sign_up_form.save()
            username = sign_up_form.cleaned_data.get('username')
            raw_password = sign_up_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('sudoku_app:play'))
            else:
                template = loader.get_template('sudoku_app/error_page.html')
                context = {
                'errors': "authentication errors",
                'target_redir_url' : str(647)
                }
                return HttpResponse(template.render(context, request))  

        else:
            game_objects = Game.objects.filter(difficulty = Game.EASY)
            sel_idx = random.randint(0,game_objects.count()-1)
            sel_id = game_objects[sel_idx].id
            template = loader.get_template('sudoku_app/error_page.html')
            context = {
                'errors': sign_up_form.errors,
                'target_redir_url' : str(sel_id)
            }
            return HttpResponse(template.render(context, request))  
    else:
        sign_up_form = SignUpForm()
        

    template = loader.get_template('sudoku_app/sign_up.html')
    context = {
        'sign_up_form' : sign_up_form
    }
    return HttpResponse(template.render(context, request))

def get_context(request, puzzle_id):
    '''
    A helper method that, given a puzzle id, returns a dictionary with
    - A game board object with hints. 
    - A game board object with the solution.
    - A form for further changes to the difficulty level. The form is initialized to the given difficulty level
    - An error code, in case the requested ID is not there or there are multiple ones (the latter should really never happen)
    - The puzzle ID itself for use by the HTML
    '''
    error_code = 0;
    puzzle_qs = Game.objects.filter(id=puzzle_id);
    if (puzzle_qs.count() == 0):error_code = 1
    if (puzzle_qs.count() >1): error_code = 1

    user_id=-1
    if request.user.is_authenticated:
        user_id = request.user.id

    if (error_code ==0):
        puzzle = puzzle_qs.get() #the actual object
        difficulty_level = puzzle.difficulty
        game_type = request.session.get('game_type')
        game_settings_form = GameSettingsForm(initial = {'difficulty_level' : difficulty_level, 'game_type' : game_type})
        ret = {
            'puzzle_hints': puzzle.hints_board,
            'puzzle_solution': puzzle.solved_board,
            'game_settings_form' : game_settings_form,
            'error_code' : error_code,
            'puzzle_id' : puzzle_id,
            'user_id' : user_id
        }
    else:
        ret = {
            'puzzle_hints': None,
            'puzzle_solution': None,
            'diff_level_form' : None,
            'error_code' : error_code,
            'puzzle_id' : puzzle_id,
            'user_id' : user_id
        }

    return ret

def new_specific_puzzle(request,puzzle_id):
    
    context = get_context(request, puzzle_id)
    if (context["error_code"] == 0):
        template = loader.get_template('sudoku_app/play.html')
        return HttpResponse(template.render(context, request))
    else:
        game_objects = Game.objects.filter(difficulty = Game.EASY)
        sel_idx = random.randint(0,game_objects.count()-1)
        sel_id = game_objects[sel_idx].id
        template = loader.get_template('sudoku_app/error_page.html')
        context = {
            'errors': 'An error was encountered. The requested puzzle number ' + str(puzzle_id) + ' does not exist.',
            'target_redir_url' : str(sel_id)
        }
        return HttpResponse(template.render(context, request))  
    

def new_puzzle_from_diff_level_change(request):
    '''
    This method is triggered by the change in level of difficulty form
    '''
    if request.method =='POST':
        form = GameSettingsForm(request.POST)
        if form.is_valid():            
            supplied_diff_level = form.cleaned_data['difficulty_level'];
            supplied_game_type= form.cleaned_data['game_type'];
            game_objects = Game.objects.filter(difficulty = supplied_diff_level)
            sel_idx = random.randint(0,game_objects.count()-1)
            sel_id = game_objects[sel_idx].id
            request.session['game_type'] = supplied_game_type;#Store the game type in the session

    return HttpResponseRedirect(reverse('sudoku_app:new_specific_puzzle',  kwargs={'puzzle_id': sel_id}));

def new_puzzle(request):
    '''
    This method is triggered by the "new game" button
    '''
    if request.method =='POST':
        
        existing_puzzle_id = int(request.POST['new_game_button'])
        existing_puzzle = Game.objects.filter(id=existing_puzzle_id).get();
        difficulty_level = existing_puzzle.difficulty
        game_objects = Game.objects.filter(difficulty = difficulty_level)
        sel_idx = random.randint(0,game_objects.count()-1)
        sel_id = game_objects[sel_idx].id

    return HttpResponseRedirect(reverse('sudoku_app:new_specific_puzzle',  kwargs={'puzzle_id': sel_id})); 

def user_page(request,user_id):
    user = User.objects.filter(id = user_id)
    user_count = user.count()
    if (user_count==1):#one user. We are good
        solved_puzzles = []
        for pzl_solved in SolvedGame.objects.filter(user__id = user_id).order_by(('-time_started')):
            
            solution_details = {
                'puzzle_id' : pzl_solved.game.id,
                'start_time' : pzl_solved.time_started,
                'duration' : pzl_solved.time_solved - pzl_solved.time_started,
                'difficulty' : pzl_solved.game.difficulty
            }
            solved_puzzles.append(solution_details)
        
        template = loader.get_template('sudoku_app/user_page.html')
        context = {
                'name': user.get().username,
                'solved_puzzles' : solved_puzzles
        }
    else:#either no user or, for whatever reason more than one..
        template = loader.get_template('sudoku_app/error_page.html')
        context = {
            'errors': 'An error was encountered. Selected user ID appears not to exist',
        }
    return HttpResponse(template.render(context, request))

def record_successful_puzzle(request):

    user_id=-1
    if request.user.is_authenticated:
        user_id = request.user.id

    if (request.method == 'POST'):

        data = json.loads(request.body)
        
        puzzle_ID = data["puzzle_ID"]
        start_year = data["start_year"]
        start_month = data["start_month"]
        start_day = data["start_day"]
        start_hour = data["start_hour"]
        start_minute = data["start_minute"]
        start_seconds = data["start_seconds"]
        
        end_year = data["end_year"]
        end_month = data["end_month"]
        end_day = data["end_day"]
        end_hour = data["end_hour"]
        end_minute = data["end_minute"]
        end_seconds = data["end_seconds"]
        zone_name = data["zone_name"]

        start_of_puzzle = datetime.datetime(year=start_year, month=start_month, day=start_day, hour=start_hour, minute=start_minute, second = start_seconds)
        end_of_puzzle = datetime.datetime(year=end_year, month=end_month, day=end_day, hour=end_hour, minute=end_minute, second = end_seconds)

        user_query = User.objects.filter(id = user_id)
        if (user_query.count()==1):
            user = user_query.get()
        puzzle_query = Game.objects.filter(id = puzzle_ID)
        if (puzzle_query.count()==1):
            puzzle = puzzle_query.get()
        
        SolvedGame.objects.create(game = puzzle, user = user, time_started = start_of_puzzle, time_solved = end_of_puzzle)

    if (user_id>0):
        return HttpResponseRedirect(reverse('sudoku_app:user_page', kwargs={'user_id' : user_id}));
    else:
        template = loader.get_template('sudoku_app/error_page.html')
        context = {
            'errors': 'An error was encountered. User id not found',
        }

sudoku_site/sudoku_app/templates/sudoku_app/app_title_div.html
<div id="header" class="header">
    <p id="header_par" class="header">
        <a class="header" href="{% url 'sudoku_app:home' %}">lisudoku.org</a>
    </p> 

    <p id="header_vertical_bar" class="header_vertical_bar"><a class="header" href="{% url 'sudoku_app:home' %}"> | </a></p>
    
    <p id="after_vertical_bar" class="header"><a class="header" href="{% url 'sudoku_app:home' %}">free online sudoku</a></p>
</div>

sudoku_site/sudoku_app/templates/sudoku_app/common_headers.html
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-COmpatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sudoku</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'login_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user_page_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home_style.css' %}">
    <link rel="stylesheet" type="text/css" media="screen and (max-width: 600px)" href="{% static 'smallscreen.css' %}">    
</head>

sudoku_site/sudoku_app/templates/sudoku_app/error_page.html
<!DOCTYPE html>
<html lang="en">
    {% include 'sudoku_app/common_headers.html' %}
    <body>
        {% include 'sudoku_app/app_title_div.html' %}
        <div class="login_overall_container">
            <p class="sign-up-title">Errors have been encountered</p>
                    <p>{{ errors }}</p>
                    <div class="button-container">
                        <button type="submit" class="check_answers_button" onclick="document.location= '/home'">Back to home page</button>
                    </div>

            </div>
        </div>
    </body>
</html>

sudoku_site/sudoku_app/templates/sudoku_app/footer.html
{% load static %}
<div class="footer">This is a free open-source website built on <a class="footer" href="https://www.djangoproject.com/">
    <img class="footer" src="{% static   'images/django-logo-positive.png' %}" alt="Django logo"></img></a>. Source code on 
    <a class="footer" href="https://github.com/albertocorrias/sudoku"><img class="footer" src="{% static   'images/GitHub-Emblem.png' %}" alt="Django logo"></img></a></div>

sudoku_site/sudoku_app/templates/sudoku_app/home.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    {% include 'sudoku_app/common_headers.html' %}
    
    <body>
        {% include 'sudoku_app/app_title_div.html' %}
        {% include 'sudoku_app/login_bar_div.html' %}
        <div class="home_page_overall_container">   
            The place for free, open-source, ads-free sudoku.             
            <div class = "home_main_container">
                <div class="home_buttons_container">
                    <form action="{% url 'sudoku_app:play' %}">
                        <input type="submit" class="home_buttons" id="play_online_id" value="Play online" />
                    </form>
                    <button type="button" class="home_buttons" id="play_offline_id" style="background-color: grey;">Play offline (coming soon)</button>
                </div>
                <div class="slide_show_container">
                      <!-- Full-width images with number and caption text -->
                        <div class="home_page_slides fade">
                            <img src="{% static   'images/sudoku_image_web_1.png' %}" style="width:100%">
                        </div>

                        <div class="home_page_slides fade">
                            <img src="{% static   'images/sudoku_image_web_2.png' %}" style="width:100%">
                        </div>

                        <div class="home_page_slides fade">
                            <img src="{% static   'images/sudoku_image_web_3.png' %}" style="width:100%">
                        </div>
                </div>
                <br>

            </div>
        </div>
        {% include 'sudoku_app/footer.html' %}
        <script src="{% static   'home_slideshow.js' %}"></script>
    </body>
</html>

sudoku_site/sudoku_app/templates/sudoku_app/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-COmpatible" content="IE=Edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sudoku</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" type="text/css" media="screen and (max-width: 600px)" href="{% static 'smallscreen.css' %}">
        <!--allow JS files to know if a user is authenticated -->
        <script type="text/javascript"> 
        {% if user.is_authenticated %}
            var user_is_logged_in = "true";
        {% else %} 
            var user_is_logged_in = "false";
        {% endif %}
         </script>
        <script src="{% static   'luxon.js' %}"></script>
        <script src="{% static   'Globals.js' %}" type="text/javascript"></script>
        <script src="{% static   'timer.js' %}" type="text/javascript"></script>
        {{puzzle_hints|json_script:"puzzle_hints"}}
        {{puzzle_solution|json_script:"puzzle_solution"}}
        <script src="{% static   'script.js' %}" type="module">
            
        </script>        

    </head>
    <body>
        {% include 'sudoku_app/app_title_div.html' %}
        
        {% include 'sudoku_app/login_bar_div.html' %}

        <div id="sudoku-game-wrapper" class="sudoku-game-wrapper">
            <div id="id_overlay_timed_results" class="overlay_timed_results">
                <p id="id_overlay_paragraph"></p>
                <button type="button" class="check_answers_button" id="id_close_timed_results_overlay_button">Close and continue</button>
            </div>
            <div id="board-wrapper" class="board-wrapper">
                <div id="game-board" class="game-board"></div>
                <div id="board-footer" class="board-footer">
                    <button type="button" class="check_answers_button" id="check_answers_button">Check your answer</button>
                    <button type="button" class="check_answers_button resume_play_button" id="resume_play_button">Resume play</button>
                </div>

            </div>
            <div id="right-controls" class="right-controls">
                {% if game_settings_form.game_type.value == "Timed" %}
                <div id = "timer-wrapper" class = "timer-wrapper">
                </div>
                {% endif %}
                <div id="game-options-wrapper" class="game-options-wrapper">
                    <form action="{% url 'sudoku_app:new_puzzle_from_diff_level_change' %}" method="post">
                        {% csrf_token %}
                        {% for field in game_settings_form %}

                            {{field.label}}: {{ field }}
                            <br/>
                        {% endfor %}
                    </form>
                </div>

                <div id = "numpad-wrapper" class="numpad-wrapper">
                    <div id = "numpad-item-1" class="numpad-item"> 1 </div>
                    <div id = "numpad-item-2" class="numpad-item"> 2 </div>
                    <div id = "numpad-item-3" class="numpad-item"> 3 </div>
                    <div id = "numpad-item-4" class="numpad-item"> 4 </div>
                    <div id = "numpad-item-5" class="numpad-item"> 5 </div>
                    <div id = "numpad-item-6" class="numpad-item"> 6 </div>
                    <div id = "numpad-item-7" class="numpad-item"> 7 </div>
                    <div id = "numpad-item-8" class="numpad-item"> 8 </div>
                    <div id = "numpad-item-9" class="numpad-item"> 9 </div>
                    <div id = "delete-button" class="numpad-item del-button"> Del </div>
                    <div id = "provisional-button" class="numpad-item"> P </div>
                </div>
                <div id="new-button-wrapper" class="new-button-wrapper">
                    <form action="{% url 'sudoku_app:new_puzzle' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" name='new_game_button' class="check_answers_button new_game_button" value="{{ puzzle_id }}">New game</button>
                    </form>
                </div>
            </div>
        </div>
        {% include 'sudoku_app/footer.html' %}
    </body>
</html>

sudoku_site/sudoku_app/templates/sudoku_app/login_bar_div.html
<div id="user_bar" class="user_bar">
    {% if user.is_authenticated %}
    You are logged in as <div id="logged_in_user" style="display:inline"><a href="{% url 'sudoku_app:user_page' user_id %}">{{ user.get_username }}</a></div>. 
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button class="check_answers_button logout_button" type="submit">Click here to logout</button>
    </form>
    {% else %}
    You are not signed in, <a href="{% url 'login'%}">login</a> or <a href="{% url 'sudoku_app:sign_up' %}">sign up</a>
    {% endif %}
</div>

sudoku_site/sudoku_app/templates/sudoku_app/play.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-COmpatible" content="IE=Edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sudoku</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" type="text/css" media="screen and (max-width: 600px)" href="{% static 'smallscreen.css' %}">
        <!--allow JS files to know if a user is authenticated -->
        <script type="text/javascript"> 
        {% if user.is_authenticated %}
            var user_is_logged_in = "true";
        {% else %} 
            var user_is_logged_in = "false";
        {% endif %}
         </script>
        <script src="{% static   'luxon.js' %}"></script>
        <script src="{% static   'Globals.js' %}" type="text/javascript"></script>
        <script src="{% static   'timer.js' %}" type="text/javascript"></script>
        {{puzzle_hints|json_script:"puzzle_hints"}}
        {{puzzle_solution|json_script:"puzzle_solution"}}
        <script src="{% static   'script.js' %}" type="module">
            
        </script>        

    </head>
    <body>
        {% include 'sudoku_app/app_title_div.html' %}
        
        {% include 'sudoku_app/login_bar_div.html' %}

        <div id="sudoku-game-wrapper" class="sudoku-game-wrapper">
            <div id="id_overlay_timed_results" class="overlay_timed_results">
                <p id="id_overlay_paragraph"></p>
                <button type="button" class="check_answers_button" id="id_close_timed_results_overlay_button">Close and continue</button>
            </div>
            <div id="board-wrapper" class="board-wrapper">
                <div id="game-board" class="game-board"></div>
                <div id="board-footer" class="board-footer">
                    <button type="button" class="check_answers_button" id="check_answers_button">Check your answer</button>
                    <button type="button" class="check_answers_button resume_play_button" id="resume_play_button">Resume play</button>
                </div>

            </div>
            <div id="right-controls" class="right-controls">
                {% if game_settings_form.game_type.value == "Timed" %}
                <div id = "timer-wrapper" class = "timer-wrapper">
                </div>
                {% endif %}
                <div id="game-options-wrapper" class="game-options-wrapper">
                    <form action="{% url 'sudoku_app:new_puzzle_from_diff_level_change' %}" method="post">
                        {% csrf_token %}
                        {% for field in game_settings_form %}

                            {{field.label}}: {{ field }}
                            <br/>
                        {% endfor %}
                    </form>
                </div>

                <div id = "numpad-wrapper" class="numpad-wrapper">
                    <div id = "numpad-item-1" class="numpad-item"> 1 </div>
                    <div id = "numpad-item-2" class="numpad-item"> 2 </div>
                    <div id = "numpad-item-3" class="numpad-item"> 3 </div>
                    <div id = "numpad-item-4" class="numpad-item"> 4 </div>
                    <div id = "numpad-item-5" class="numpad-item"> 5 </div>
                    <div id = "numpad-item-6" class="numpad-item"> 6 </div>
                    <div id = "numpad-item-7" class="numpad-item"> 7 </div>
                    <div id = "numpad-item-8" class="numpad-item"> 8 </div>
                    <div id = "numpad-item-9" class="numpad-item"> 9 </div>
                    <div id = "delete-button" class="numpad-item del-button"> Del </div>
                    <div id = "provisional-button" class="numpad-item"> P </div>
                </div>
                <div id="new-button-wrapper" class="new-button-wrapper">
                    <form action="{% url 'sudoku_app:new_puzzle' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" name='new_game_button' class="check_answers_button new_game_button" value="{{ puzzle_id }}">New game</button>
                    </form>
                </div>
            </div>
        </div>
        {% include 'sudoku_app/footer.html' %}
    </body>
</html>

sudoku_site/sudoku_app/templates/sudoku_app/sign_up.html
<!DOCTYPE html>
<html lang="en">
    {% include 'sudoku_app/common_headers.html' %}
    <body>
        {% include 'sudoku_app/app_title_div.html' %}
        <div class="login_overall_container">
            <p class="sign-up-title">Sign up. It's free!</p>
            <div class="form-container">
                <form method="post">
                    {% csrf_token %}
                    {% for field in sign_up_form %}
                        <p>{{ field.label_tag }} {{ field }}</p>
                        <p class="help-text"> {{ field.help_text }} </p>
                        
                    {% endfor %}
                    <div class="button-container">
                        <button type="submit" class="check_answers_button">Sign up</button>
                    </div>
                </form>
            </div>
        </div>
        {% include 'sudoku_app/footer.html' %}
    </body>
</html>

sudoku_site/sudoku_app/templates/sudoku_app/user_page.html
<!DOCTYPE html>
<html lang="en">
    {% include 'sudoku_app/common_headers.html' %}
    <body>
        {% include 'sudoku_app/app_title_div.html' %}

        <div class="login_overall_container">
            <p class="user-title"> {{ name }}'s user page </p>
            
            <div class="user-table-container">
                <table class="user-table">
                    <thead>
                    <tr><th colspan=4 class="top-title-row">Puzzles solved in a timed session</th></tr>
                    <tr> 
                        <th>Puzzle number</th>
                        <th>Difficulty</th>
                        <th>Time taken to solve</th>
                        <th>Date and time</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for entry in solved_puzzles %}
                        <tr>
                        <td>{{ entry.puzzle_id }}</td> 
                        <td>{{ entry.difficulty }}</td> 
                        <td>{{ entry.duration }}</td>
                        <td>{{ entry.start_time }}</td> 
                        </tr>
                        {% endfor %}
                    </tbody>

                </table>
            </div>

            
        </div>
    </body>
</html>